export const CHANGE_REGISTER_FORM_CONTROL = "CHANGE_REGISTER_FORM_CONTROL";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const CHANGE_FORM_ERROR_MESSAGE = "CHANGE_FORM_ERROR_MESSAGE";
export const CHANGE_LOG_IN_FORM_CONTROL = "CHANGE_LOG_IN_FORM_CONTROL";
export const LOG_IN = "LOG_IN";
