export const CHANGE_REGISTER_FORM_CONTROL = "CHANGE_REGISTER_FORM_CONTROL";
export const REGISTER_ACCOUNT_SUCCESS = "REGISTER_ACCOUNT_SUCCESS";
export const CHANGE_REGISTRATION_FORM_ERROR_MESSAGE =
  "CHANGE_REGISTRATION_FORM_ERROR_MESSAGE";
export const CHANGE_LOG_IN_FORM_CONTROL = "CHANGE_LOG_IN_FORM_CONTROL";
export const CHANGE_LOG_IN_FORM_ERROR = "CHANGE_LOG_IN_FORM_ERROR";
export const DELETE_USER = "DELETE_USER";
export const CHANGE_USER = "CHANGE_USER";
export const GET_USERS = "GET_USERS";
